Project/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tourism.urls', namespace='tourism')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourism/urls.py
from django.conf.urls import url
from tourism import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.Login, name='Login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^user_bookings/$', views.user_bookings, name='user_bookings'),
    url(r'^remove/(?P<pk>.+)/$', views.remove_booking, name='remove_booking'),

    url(r'^payment/(?P<pk>.+)/$', views.payment, name='payment'),
    url(r'^payment/success$', views.payment_success, name="payment_success"),
    url(r'^payment/failure$', views.payment_failure, name="payment_failure"),

]

tourism/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.


class Mobile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Mobile_Number = models.CharField(max_length=15,default=0)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_mobile(sender, instance, created, **kwargs):
        if created:
            Mobile.objects.create(user=instance)

class Packages(models.Model):
    Picture = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=None, blank=True, null=True)
    width_field = models.IntegerField(default=None, blank=True, null=True)
    location = models.CharField(max_length=20)
    Price = models.IntegerField()
    Description = models.TextField()

    def __str__(self):
        return self.location

class Bookings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    package = models.ForeignKey(Packages, on_delete=models.CASCADE)
    is_Paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

tourism/forms.py
from django import forms
from .models import Mobile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'email',)

    def __init__(self, *args, **kwargs):

        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            username ="username"
            help_text = self.fields[field].help_text
            self.fields[field].help_text = None
            if help_text != '':
                self.fields[field].widget.attrs.update(
                    {'class': 'has-popover', 'data-content' :help_text, 'data-placement': 'right',
                     'data-container': 'body'})
                self.fields[username].widget.attrs.update(
                    {'id': username})

                # to ensure that the user email is unique
    # def clean_email(self):
    #     if User.objects.filter(email=self.cleaned_data.get('email', None)).count() > 0:
    #         raise forms.ValidationError("User with this email already exists")

    #     return self.cleaned_data.get('email')

class MobileForm(forms.ModelForm):
    Mobile_Number = forms.CharField(max_length=15,required=True)
    class Meta:
        model = Mobile
        fields = ('Mobile_Number',)

tourism/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Mobile
from django.contrib.auth import login
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .forms import SignUpForm, MobileForm
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.forms import AuthenticationForm
import smtplib
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from .models import Packages, Bookings
from django.contrib.auth.decorators import login_required
from django.conf import settings
import logging, traceback
from django.core.urlresolvers import reverse
import hashlib
from random import randint
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

PAID_FEE_AMOUNT = 0

# Create your views here.
def home(request):
    return render(request, 'tourism/index.html')


# ------------For Users -------------
def signup(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        mobile_form = MobileForm(request.POST)
        if user_form.is_valid() and mobile_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = False
            user.save()

            user.mobile.Mobile_Number = mobile_form.cleaned_data.get('Mobile_Number')
            user.mobile.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Destino Account'
            message = render_to_string('tourism/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return render(request, 'tourism/account_activation_sent.html')
        else:
            print(user_form)
            redirect(request.META['HTTP_REFERER'])

    else:
        user_form = SignUpForm()
        mobile_form = MobileForm()
    context = {
        "user_form": user_form,
        "Mobile_form": mobile_form,
        'errors': user_form.errors,
    }
    return render(request, 'tourism/account_registrations.html', context)


def account_activation_sent(request):
    return render(request, 'tourism/account_activation_sent.html')


def activate(request, uidb64, token, ):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.mobile.email_confirmed = True
        user.mobile.save()
        user.save()
        login(request, user, backend='django.core.mail.backends.smtp.EmailBackend')
        return redirect('tourism:home')
    else:
        return render(request, 'tourism/account_activation_invalid.html')


def Login(request):
    error_message = ""

    if request.method == 'POST':
        login_form = AuthenticationForm(request.POST or None)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('tourism:user_profile')
        else:

            error_message = "Incorrect username or password."
            messages.error(request, error_message)
            login_form = AuthenticationForm(request.POST or None)

    else:
        login_form = AuthenticationForm()
    return render(request, 'tourism/account_registrations.html', {'login_form': login_form, 'error_message': error_message})

def user_profile(request):
    query = request.GET.get("q")
    queryset_list = Packages.objects.all().order_by('Price')
    if query:
        queryset_list = queryset_list.filter(Q(location__icontains=query)).distinct().order_by('Price')

   
    paginator = Paginator(queryset_list, 3)
    page_change_var = 'page'  # change=request
    page = request.GET.get(page_change_var)
    try:
        queryset_list = paginator.page(page)
    except PageNotAnInteger:
        queryset_list = paginator.page(1)
    except EmptyPage:
        queryset_list = paginator.page(paginator.num_pages)

    context = {
        'page_change_var':page_change_var,
        'packages':queryset_list,
    }
    return render(request, 'tourism/user_profile.html', context)


def user_bookings(request):
    bookings = Bookings.objects.filter(user=request.user)

    context = {
        'bookings': bookings
    }
    return render(request, 'tourism/user_bookings.html', context)

def remove_booking(request,pk):
    instance = Bookings.objects.get(pk=pk)
    instance.delete()
    return redirect('tourism:user_bookings')

@login_required
def payment(request, pk):
    get_package = Packages.objects.get(pk=pk)
    global PAID_FEE_AMOUNT
    PAID_FEE_AMOUNT=get_package.Price
    user = request.user
    get_user = get_object_or_404(User, username=user)
    data = {}
    txnid = get_transaction_id(request)
    hash_ = generate_hash(request, txnid)
    hash_string = get_hash_string(request, txnid)
    
    # use constants file to store constant values.
    # use test URL for testing
    data["action"] = settings.PAYMENT_URL_LIVE #LIVE for production
    data["productinfo"] = settings.PAID_FEE_PRODUCT_INFO
    data["key"] = settings.KEY
    data["txnid"] = txnid
    data["hash"] = hash_
    data["hash_string"] = hash_string
    data["amount"] = float(PAID_FEE_AMOUNT)
    data["firstname"] = get_user.first_name
    if get_user.email:
        data["email"] = get_user.email
    try:
        if get_user.mobile.Mobile_Number:
            data["phone"] = get_user.mobile.Mobile_Number
    except:
        print("Mobile number not present")
    data["service_provider"] = settings.SERVICE_PROVIDER
    data["furl"] = request.build_absolute_uri(reverse("tourism:payment_failure"))
    data["surl"] = request.build_absolute_uri(reverse("tourism:payment_success"))
    instance = Bookings.objects.create(user=get_user, package=get_package, is_Paid=False)
    instance.save()
    return render(request, "tourism/success.html", data)


# generate the hash
@login_required
def generate_hash(request, txnid):
    try:
        # get keys and SALT from dashboard once account is created.
        #hashSequence = "key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5|udf6|udf7|udf8|udf9|udf10"
        hash_string = get_hash_string(request, txnid)
        #print(hash_string)
        generated_hash = hashlib.sha512(hash_string.encode('utf-8')).hexdigest().lower()
        return generated_hash
    except Exception as e:
        # log the error here.
        logging.getLogger("error_logger").error(traceback.format_exc())
        return None


# create hash string using all the fields
@login_required
def get_hash_string(request, txnid):
    get_user = get_object_or_404(User, username=request.user)

    get_socialauth_user=get_user
   
    hash_string = settings.KEY + "|" + txnid + "|" + str(
        float(PAID_FEE_AMOUNT)) + "|" + settings.PAID_FEE_PRODUCT_INFO + "|"

    if get_user.email:
        hash_string += get_user.first_name + "|" + get_user.email + "|"
    else:
        hash_string += get_user.first_name + "|" + get_socialauth_user.uid + "|"

    hash_string += "||||||||||" + settings.SALT

    return hash_string


# generate a random transaction Id.
@login_required
def get_transaction_id(request):
    hash_object = hashlib.sha256(str(randint(0, 9999)).encode("utf-8"))
    # take approprite length
    txnid = hash_object.hexdigest().lower()[0:32]
    return txnid


# no csrf token require to go to Success page.
# This page displays the success/confirmation message to user indicating the completion of transaction.
@csrf_exempt
@login_required
def payment_success(request):
   return render(request, "tourism/paysuccess.html")


# no csrf token require to go to Failure page. This page displays the message and reason of failure.
@login_required
@csrf_exempt
def payment_failure(request):
    return render(request, "tourism/payfail.html")

tourism/templates/tourism/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:
If the link does not appear clickable then copy the link and open it on new tab.

http://{{ domain }}{% url 'tourism:activate' uidb64=uid token=token %}
{% endautoescape %}

tourism/templates/tourism/account_activation_invalid.html
{% extends 'tourism/base.html' %}
{% load staticfiles %}
{% block content %}
<div id="peace-layout">
    <h2 align="center">The confirmation link was invalid, possibly because it has already been used.</h2>
</div>
{% endblock %}

tourism/templates/tourism/account_registrations.html
{% extends 'tourism/base.html' %}
{% load staticfiles %}
{% block content %}

    <div id="peace-layout" style="margin-top: 100px">

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/account_registrations.css' %}">
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!------ Include the above in your HEAD tag ---------->

        <script src="{% static 'js/account_registrations.js' %}"></script>
        {% if errors %}
            <script>
                $(document).ready(function () {
                    $("#register-form-link").trigger('click');


                });
            </script>
        {% endif %}

        <div class="container" style="margin-bottom: 20px !important;">
            <div class="row">
                <div class="col-md-6 offset-3">
                    <div class="panel panel-login">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="#login-form" class="active" id="login-form-link">Login</a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="#register-form" id="register-form-link">Register</a>
                                </div>
                            </div>
                            <hr>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form id="login-form" action="{% url 'tourism:Login' %}" method="post"
                                          role="form"
                                          style="display: block;">
                                        {% csrf_token %}
                                        {% if error_message %}

                                            <div class="alert alert-danger">
                                                {{ error_message }}
                                            </div>

                                        {% endif %}
                                        <div class="form-group">
                                            <input type="text" name="username" id="username" tabindex="1"
                                                   class="form-control"
                                                   placeholder="Username" value="{% if login_form.username.value %}{{ login_form.username.value }}{% endif %}"
                                                   required>

                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" id="password" tabindex="2"
                                                   class="form-control" placeholder="Password" value="{% if login_form.password.value %}{{ login_form.password.value }}{% endif %}"
                                                   required>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6 col-sm-offset-3">
                                                    <input type="submit" name="login-submit" id="login-submit"
                                                           tabindex="4"
                                                           class="form-control btn btn-login" value="Log In">
                                                </div>
                                            </div>
                                        </div>
{#                                        <div class="form-group">#}
{#                                            <div class="row">#}
{#                                                <div class="col-lg-12">#}
{#                                                    <div class="text-center">#}
{#                                                        <a href=""#}
{#                                                           tabindex="5"#}
{#                                                           class="forgot-password">Forgot Password?</a>#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="form-group">#}
{#                                            <div class="row">#}
{#                                                <div class="col-lg-5 col-lg-offset-1">#}
{#                                                    <a href="{% url 'social:begin' 'facebook' %}">Login with#}
{#                                                        Facebook</a>#}
{#                                                </div>#}
{#                                                <div class="col-lg-5 col-lg-offset-1">#}
{#                                                    <a href="{% url 'social:begin' 'google-oauth2' %}">Login with#}
{#                                                        Gmail</a>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
                                    </form>
                                    <form id="register-form" action="{% url 'tourism:signup' %}"
                                          method="post"
                                          role="form" style="display: none;">{% csrf_token %}

                                        <div class="form-group">
                                            <input type="text" name="first_name" id="first-name-signup" tabindex="1"
                                                   class="form-control"
                                                   placeholder="First Name" value="{% if user_form.first_name.value %}{{ user_form.first_name.value }}{% endif %}"
                                                   required>
                                            {% if user_form.first_name.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.first_name.errors }}
                                                </div>
                                            {% endif %}

                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="last_name" id="last-name-signup" tabindex="1"
                                                   class="form-control"
                                                   placeholder="Last Name" value="{% if user_form.last_name.value %}{{ user_form.last_name.value }}{% endif %}"
                                                   required>
                                            {% if user_form.last_name.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.last_name.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="username" id="username-signup" tabindex="1"
                                                   class="form-control"
                                                   placeholder="Username" value="{% if user_form.username.value %}{{ user_form.username.value }}{% endif %}"
                                                   required>
                                            {% if user_form.username.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.username.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="form-group">
                                            <input type="email" name="email" id="email" tabindex="1"
                                                   class="form-control"
                                                   placeholder="Email Address" value="{% if user_form.email.value %}{{ user_form.email.value }}{% endif %}"
                                                   required>
                                            {% if user_form.email.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.email.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password1" id="id_password1" tabindex="2"
                                                   class="form-control" placeholder="Password" value="{% if user_form.password1.value %}{{ user_form.password1.value }}{% endif %}"
                                                   required>
                                            {% if user_form.password1.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.password1.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password2" id="id_password2" tabindex="2"
                                                   class="form-control" placeholder="Confirm Password" value="{% if user_form.password2.value %}{{ user_form.password2.value }}{% endif %}"
                                                   required>
                                            {% if user_form.password2.errors %}
                                                <div class="alert alert-danger">
                                                    {{ user_form.password2.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="Mobile_Number" id="id_Mobile_Number" tabindex="2"
                                                   class="form-control" placeholder="Mobile Number" value="{% if Mobile_form.Mobile_Number.value %}{{ Mobile_form.Mobile_Number.value }}{% endif %}"
                                                   required>
                                            {% if Mobile_form.Mobile_Number.errors %}
                                                <div class="alert alert-danger">
                                                    {{ Mobile_form.Mobile_Number.errors }}
                                                </div>
                                            {% endif %}

                                        </div>
{#                                        <div class="form-group">#}
{#                                            <select name="usertype"#}
{#                                                    style=" height: 45px;border: 1px solid #ddd;border-radius: 3px;"#}
{#                                                    class="form-control" required>#}
{#                                                <option value="" disabled selected>SignUp as</option>#}
{#                                                <option value="user">User</option>#}
{#                                                <option value="seller">Seller</option>#}
{#                                                <option value="pandit">Pandit</option>#}
{#                                            </select>#}
{#                                        </div>#}
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6 col-sm-offset-3">
                                                    <input type="submit" name="register-submit" id="register-submit"
                                                           tabindex="4" class="form-control btn btn-register"
                                                           value="Register Now">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tourism/templates/tourism/payfail.html
{% extends 'tourism/base.html' %}
{% load staticfiles %}

{% block title %}
    Oops
{% endblock %}

{% block content %}
    <div id="peace-layout">

        <div class="container" style="margin-top: 200px;">
            <div class="row">
                <div class="col-md-12" align="center">
                    <h1>Oopps</h1>
                    <p>Your payment has Failed.Try Again</p>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

tourism/templates/tourism/paysuccess.html
{% extends 'tourism/base.html' %}
{% load staticfiles %}

{% block title %}
    Thank You
{% endblock %}

{% block content %}
    <div id="peace-layout" style="margin-top: 200px;">
        <h1>Thank You</h1>
        <br>
        <p>Your transaction is successfully completed.</p>
    </div>
    <br>
    <br>
{% endblock %}